export const STORAGE_KEYS = {
  CSS_STYLE_KEY: 'CSS_STYLE_KEY',
  UNIT_TYPE_KEY: 'UNIT_TYPE_KEY',
  USER_COMPONENT_SETTINGS_KEY: 'USER_COMPONENT_SETTINGS_KEY',
  UPDATE_NODE_PROPERTIES_KEY: 'UPDATE_NODE_PROPERTIES_KEY',
  PROVIDER_SETTINGS_KEY: 'PROVIDER_SETTINGS_KEY'
} as const
