export enum FluentComponentType {
  PrimaryButton = 'PrimaryButton',
  DefaultButton = 'DefaultButton',
  Link = 'Link',
  SearchBox = 'SearchBox',
  TextField = 'TextField',
  Dropdown = 'Dropdown',
  SpinButton = 'SpinButton',
  CheckBox = 'CheckBox',
  ChoiceGroup = 'ChoiceGroup',
  Toggle = 'Toggle',
  DetailsList = 'DetailsList',
  IconButton = 'IconButton',
  Label = 'Label',
  Stack = 'Stack',
}
